[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
  out
  | libs
  | env
  | venv
  | .venv
)/
'''

[tool.isort]
line_length = 120
force_single_line = true
skip = ['out', 'env', 'venv', '.venv', 'libs']